# -*- coding: utf-8 -*-
"""Aula2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M_R6qWztmOE-EygdaQpgTLunNJBYY5bC
"""

resposta = input('voce deseja ir a outra tela?')
if resposta =='sim':
   print('voce foi para outra tela')
else:
     print('voce saiu do sistema')

nome = input('informe o nome de usuario:')
sexo = input("informe 'F' para femenino e 'M' para masculino:").upper()
if (sexo == 'M'):
    sexo ='o'
elif(sexo == 'F'):
   sexo = 'A'
usuario = int(input('informe o tipo de usario \n 1 - para administrador \n 2 - para usario comum \n 3 - para membro associado'))
if(usuario == 1):
    usuario = 'administrador do sistema'
elif(usuario == 3):
    usuario = 'membro associado'
elif(usuario == 2):
    usuario = 'usuario comum'
else:
    usuario = 'nao inexistente'
    
print(f'seja bem vind{sexo} {nome}, a sua licença é de {usuario}')